application: explore-venues
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on 

handlers:

- url: /
  static_files: scripts/main.html
  upload: .html

- url: .*
  static_dir: scripts


